backend:
  name: github
  repo: jordanwhitestephenson/ubiquitous-train
  branch: main

media_folder: content/assets
public_folder: ../assets

collections:
  - name: blog
    label: Blog
    folder: content/blog
    path: '{{title}}/index'
    create: true
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
      - { name: image, label: Image, widget: image }
      - { name: select, label: Select, widget: select,  options: ["dev", "design", "productManagement"]}

       